version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/server:/app
    environment:
      - MAIN_PATH=/project/backend/server
      - UPLOADS_PATH=/project/backend/uploaded
      - CHAIN_PATH=/project/backend/internal/chain
      - GENFILE=generator.py
      - DURATION=900
      - MAX_REQUEST_PER_IP=3
      - MAX_PROMPT_LENGTH=150